/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasPemvis;

/**
 *
 * @author Dr. Kudrat Sunandar
 */
public class ModulLima extends javax.swing.JFrame {

    /**
     * Creates new form ModulLima
     */
    public ModulLima() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNama = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        lAlamat = new javax.swing.JLabel();
        jAlamat = new javax.swing.JTextField();
        lMakanan = new javax.swing.JLabel();
        cbSpa = new javax.swing.JCheckBox();
        cbCheese = new javax.swing.JCheckBox();
        cbChoco = new javax.swing.JCheckBox();
        lMinuman = new javax.swing.JLabel();
        cbCar = new javax.swing.JCheckBox();
        cbLatte = new javax.swing.JCheckBox();
        cbFrappe = new javax.swing.JCheckBox();
        bPesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNama.setText("Nama:");

        lAlamat.setText("Alamat:");

        lMakanan.setText("Makanan");

        cbSpa.setText("Spaghetti Aglio Olio");
        cbSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpaActionPerformed(evt);
            }
        });

        cbCheese.setText("Cheesecake");

        cbChoco.setText("Choco Lava");

        lMinuman.setText("Minuman");

        cbCar.setText("Caramel Macchiato");

        cbLatte.setText("Latte");

        cbFrappe.setText("Frappe");

        bPesan.setText("Pesan");
        bPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesanActionPerformed(evt);
            }
        });

        txtPesan.setEditable(false);
        txtPesan.setColumns(20);
        txtPesan.setRows(5);
        txtPesan.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtPesan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSpa)
                            .addComponent(cbCheese)
                            .addComponent(cbChoco))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFrappe)
                            .addComponent(cbLatte)
                            .addComponent(cbCar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNama, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lMakanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lMinuman)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(bPesan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lMakanan)
                        .addComponent(lMinuman))
                    .addComponent(lNama))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lAlamat)
                            .addComponent(jAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cbSpa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cbCar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCheese)
                            .addComponent(cbLatte))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChoco)
                    .addComponent(cbFrappe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bPesan)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSpaActionPerformed

    private void bPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesanActionPerformed
        String nama = jNama.getText();
    String alamat = jAlamat.getText();
    
    // Membuat StringBuilder untuk menampung pesanan
    StringBuilder pesanan = new StringBuilder();
    pesanan.append("Nama: ").append(nama).append("\n");
    pesanan.append("Alamat: ").append(alamat).append("\n");
    
    // Mengecek makanan yang dipilih
    pesanan.append("Makanan:\n");
    if (cbSpa.isSelected()) {
        pesanan.append("- Spaghetti Aglio Olio\n");
    }
    if (cbCheese.isSelected()) {
        pesanan.append("- Cheesecake\n");
    }
    if (cbChoco.isSelected()) {
        pesanan.append("- Choco Lava\n");
    }
  
    
    // Mengecek minuman yang dipilih
    pesanan.append("Minuman:\n");
    if (cbCar.isSelected()) {
        pesanan.append("- Caramel Macchiato\n");
    }
    if (cbLatte.isSelected()) {
        pesanan.append("- Latte\n");
    }
    if (cbFrappe.isSelected()) {
        pesanan.append("- Frappe\n");
    }

    // Menampilkan pesanan pada JTextArea
    txtPesan.setText(pesanan.toString());
    }//GEN-LAST:event_bPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModulLima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModulLima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModulLima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModulLima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModulLima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPesan;
    private javax.swing.JCheckBox cbCar;
    private javax.swing.JCheckBox cbCheese;
    private javax.swing.JCheckBox cbChoco;
    private javax.swing.JCheckBox cbFrappe;
    private javax.swing.JCheckBox cbLatte;
    private javax.swing.JCheckBox cbSpa;
    private javax.swing.JTextField jAlamat;
    private javax.swing.JTextField jNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lMakanan;
    private javax.swing.JLabel lMinuman;
    private javax.swing.JLabel lNama;
    private javax.swing.JTextArea txtPesan;
    // End of variables declaration//GEN-END:variables
}
